# syntax=docker/dockerfile:1
FROM golang:1.23-alpine

# Install tzdata and swag early
RUN apk add --no-cache tzdata && \
    go install github.com/swaggo/swag/cmd/swag@latest

ENV TZ=Africa/Abidjan
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

# Copy only the go.mod and go.sum files first
COPY go.mod go.sum ./

# Download and tidy dependencies
RUN go mod download && go mod tidy

# Now copy the rest of the source code
COPY . .

# Vendor dependencies
RUN go mod vendor

# Generate swagger docs from root directory
RUN swag init

# Build the application
RUN go build -o /{{ .ServiceName }}

EXPOSE 8080 8081

CMD ["/{{ .ServiceName }}"] 