package generator

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/Choplife-group/gomicrogen/internal/config"
)

func TestShouldSkipFile(t *testing.T) {

	cases := []struct {
		name string
		path string
		skip bool
	}{
		{"go.sum is regenerated by tidy", "go.sum", true},
		{"macOS metadata never belongs in a service", ".DS_Store", true},
		{"nested macOS metadata", "app/router/.DS_Store", true},
		{"a tmp directory in the template tree", "tmp/thing.go", true},
		{"a nested tmp directory", "app/tmp/thing.go", true},
		{"ordinary Go file", "app/router/router.go", false},
		{"template file", "main.go.tmpl", false},
		// generated protobuf must reach the service: the overlays ship gRPC clients
		{"protobuf is emitted, not skipped", "app/grpc/wallet/wallet-service.pb.go", false},
		{"grpc protobuf variant", "app/grpc/casino/casino-service_grpc.pb.go", false},
		// a directory merely containing the word must not be skipped
		{"directory containing tmp as substring", "app/tmpl-helpers/x.go", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := shouldSkipFile(tc.path); got != tc.skip {
				t.Errorf("shouldSkipFile(%q) = %v, want %v", tc.path, got, tc.skip)
			}
		})
	}
}

func TestShouldCopyAsIs(t *testing.T) {

	cases := []struct {
		path string
		copy bool
	}{
		{"docs/docs.go", true},
		{"docs/swagger.json", true},
		{"docs/swagger.yaml", true},
		// protobuf must not go through text/template
		{"app/grpc/wallet/wallet-service.pb.go", true},
		{"app/grpc/casino/casino-service_grpc.pb.go", true},
		{"app/router/router.go", false},
		{"main.go.tmpl", false},
	}

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			if got := shouldCopyAsIs(tc.path); got != tc.copy {
				t.Errorf("shouldCopyAsIs(%q) = %v, want %v", tc.path, got, tc.copy)
			}
		})
	}
}

// A templates directory living under a path with a "tmp" ancestor must still
// generate. Matching the absolute path once made this produce zero files while
// reporting success.
func TestRenderTreeUnaffectedByTmpAncestorInAbsolutePath(t *testing.T) {

	root := filepath.Join(t.TempDir(), "tmp", "install", "templates")

	base := filepath.Join(root, "base")
	if err := os.MkdirAll(base, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(base, "main.go.tmpl"), []byte("package {{ .ServiceName }}"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	target := t.TempDir()

	cfg := config.NewServiceConfig("svc")
	gen := NewTemplateGenerator(ResolveLayout(root), "", cfg)

	if err := gen.GenerateService(target); err != nil {
		t.Fatalf("generate: %v", err)
	}

	if _, err := os.Stat(filepath.Join(target, "main.go")); err != nil {
		t.Fatal("no files generated: a tmp ancestor in the templates path must not skip everything")
	}
}

// An overlay file replaces the base file at the same relative path, and the
// .tmpl suffix is stripped from the target so either side may use it.
func TestOverlayReplacesBaseFile(t *testing.T) {

	root := t.TempDir()

	base := filepath.Join(root, "base", "app")
	overlay := filepath.Join(root, "types", "casino", "app")

	for _, dir := range []string{base, overlay} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
	}

	if err := os.WriteFile(filepath.Join(base, "shared.go.tmpl"), []byte("BASE"), 0o644); err != nil {
		t.Fatalf("write base: %v", err)
	}
	if err := os.WriteFile(filepath.Join(base, "only-in-base.go"), []byte("KEPT"), 0o644); err != nil {
		t.Fatalf("write base only: %v", err)
	}
	// overlay uses the bare name; the base used .tmpl. Both land on shared.go.
	if err := os.WriteFile(filepath.Join(overlay, "shared.go"), []byte("OVERLAY"), 0o644); err != nil {
		t.Fatalf("write overlay: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "types", "casino", "type.json"), []byte(`{"description":"x"}`), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}

	target := t.TempDir()

	layout := ResolveLayout(root)
	cfg := config.NewServiceConfig("svc")
	cfg.Type = "casino"

	gen := NewTemplateGenerator(layout, filepath.Join(layout.TypesDir, "casino"), cfg)
	if err := gen.GenerateService(target); err != nil {
		t.Fatalf("generate: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, "app", "shared.go"))
	if err != nil {
		t.Fatalf("read shared.go: %v", err)
	}
	if string(got) != "OVERLAY" {
		t.Errorf("shared.go = %q, want the overlay to replace the base file", got)
	}

	if _, err := os.Stat(filepath.Join(target, "app", "only-in-base.go")); err != nil {
		t.Error("base-only files must survive the overlay pass")
	}

	// the overlay manifest is generator metadata, not service content
	if _, err := os.Stat(filepath.Join(target, "type.json")); err == nil {
		t.Error("type.json must not be emitted into the generated service")
	}
}

// Even in legacy mode, where BaseDir is the templates root itself, the
// scaffolding directories must never be emitted into a service.
func TestBaseWalkNeverEmitsScaffolding(t *testing.T) {

	root := t.TempDir()

	for _, dir := range []string{"base", filepath.Join("types", "casino")} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "base", "main.go.tmpl"), []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "types", "casino", "leak.go"), []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	target := t.TempDir()

	cfg := config.NewServiceConfig("svc")
	gen := NewTemplateGenerator(Layout{Root: root, BaseDir: root, Legacy: true}, "", cfg)

	if err := gen.GenerateService(target); err != nil {
		t.Fatalf("generate: %v", err)
	}

	for _, leaked := range []string{"base", "types"} {
		if _, err := os.Stat(filepath.Join(target, leaked)); err == nil {
			t.Errorf("%s/ leaked into the generated service", leaked)
		}
	}
}

func TestTemplateValuesAreSubstituted(t *testing.T) {

	root := t.TempDir()

	base := filepath.Join(root, "base")
	if err := os.MkdirAll(base, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	body := "svc={{ .ServiceName }} mod={{ .ModuleName }} port={{ .Port }} pg={{ .IsPostgres }}"
	if err := os.WriteFile(filepath.Join(base, "out.txt.tmpl"), []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	target := t.TempDir()

	cfg := config.NewServiceConfig("my-svc")
	cfg.ModuleName = "github.com/org/my-svc"
	cfg.Port = "9999"
	cfg.DatabaseDriver = config.DriverPostgres

	gen := NewTemplateGenerator(ResolveLayout(root), "", cfg)
	if err := gen.GenerateService(target); err != nil {
		t.Fatalf("generate: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(target, "out.txt"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	want := "svc=my-svc mod=github.com/org/my-svc port=9999 pg=true"
	if string(got) != want {
		t.Errorf("got  %q\nwant %q", got, want)
	}
}
